default
{
	state_entry()
	{
		list res;
		res = lsGetWindlightScene([
			WL_WATER_COLOR,
			WL_WATER_FOG_DENSITY_EXPONENT,
			WL_UNDERWATER_FOG_MODIFIER,
			WL_REFLECTION_WAVELET_SCALE,
			WL_FRESNEL_SCALE,
			WL_FRESNEL_OFFSET,
			WL_REFRACT_SCALE_ABOVE,
			WL_REFRACT_SCALE_BELOW,
			WL_BLUR_MULTIPLIER,
			WL_BIG_WAVE_DIRECTION,
			WL_LITTLE_WAVE_DIRECTION,
			WL_NORMAL_MAP_TEXTURE,
			WL_HORIZON,
			WL_HAZE_HORIZON,
			WL_BLUE_DENSITY,
			WL_HAZE_DENSITY,
			WL_DENSITY_MULTIPLIER,
			WL_DISTANCE_MULTIPLIER,
			WL_MAX_ALTITUDE,
			WL_SUN_MOON_COLOR,
			WL_AMBIENT,
			WL_EAST_ANGLE,
			WL_SUN_GLOW_FOCUS,
			WL_SUN_GLOW_SIZE,
			WL_SCENE_GAMMA,
			WL_STAR_BRIGHTNESS,
			WL_CLOUD_COLOR,
			WL_CLOUD_XY_DENSITY,
			WL_CLOUD_COVERAGE,
			WL_CLOUD_SCALE,
			WL_CLOUD_DETAIL_XY_DENSITY,
			WL_CLOUD_SCROLL_X,
			WL_CLOUD_SCROLL_Y,
			WL_CLOUD_SCROLL_X_LOCK,
			WL_CLOUD_SCROLL_Y_LOCK,
			WL_DRAW_CLASSIC_CLOUDS,
			WL_SUN_MOON_POSITION]);
		
		lsSetWindlightScene([]);
		
		lsClearWindlightScene();
		
		lsSetWindlightSceneTargeted([], NULL_KEY);
	}
}
