default
{
	state_entry()
	{
		llRequestPermissions(NULL_KEY, PERMISSION_DEBIT | PERMISSION_TAKE_CONTROLS | PERMISSION_TRIGGER_ANIMATION | PERMISSION_ATTACH | PERMISSION_CHANGE_LINKS | PERMISSION_TRACK_CAMERA | PERMISSION_CONTROL_CAMERA | PERMISSION_TELEPORT | PERMISSION_SILENT_ESTATE_MANAGEMENT | PERMISSION_OVERRIDE_ANIMATIONS | PERMISSION_RETURN_OBJECTS);
		integer i = llGetPermissions();
		key k = llGetPermissionsKey();
	}
}